apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dpf-hcp-provisioner-operator.fullname" . }}-pod-reader
  namespace: {{ include "dpf-hcp-provisioner-operator.namespace" . }}
  labels:
    {{- include "dpf-hcp-provisioner-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dpf-hcp-provisioner-operator.fullname" . }}-pod-reader-binding
  namespace: {{ include "dpf-hcp-provisioner-operator.namespace" . }}
  labels:
    {{- include "dpf-hcp-provisioner-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dpf-hcp-provisioner-operator.fullname" . }}-pod-reader
subjects:
- kind: ServiceAccount
  name: {{ include "dpf-hcp-provisioner-operator.serviceAccountName" . }}
  namespace: {{ include "dpf-hcp-provisioner-operator.namespace" . }}
